projectID: "datcom-internal"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-internal-dev-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
bucket: "datcom-internal-dev-resources"
gcfSA: "datcom-internal@appspot.gserviceaccount.com"
skipNamesInSvgCache: "true"
processCapacitor: "true"
