projectID: "datcom-stanford"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/csv_to_bt"
bucket: "datcom-stanford-resources"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
