projectID: "datcom-feedingamerica"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-stanford-resources/dataflow/tmp"
bucket: "datcom-feedingamerica-resources"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
gcfSA: "website-robot@datcom-feedingamerica.iam.gserviceaccount.com"
