projectID: "datcom-mixer-encode"
instance: "dc-graph"
cluster: "dc-graph-c1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-mixer-encode-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
bucket: "datcom-mixer-encode-resources"
gcfSA: "website-robot@datcom-mixer-encode.iam.gserviceaccount.com"
