projectID: "datcom-magiceye-dev"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-magiceye-dev-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-magiceye"
bucket: "datcom-magiceye-dev-resources"
gcfSA: "website-robot@datcom-magiceye-dev.iam.gserviceaccount.com"
