projectID: "google.com:datcom-store-dev"
instance: "prophet-test"
cluster: "prophet-test-c1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
dataPath: "gs://prophet_cache"
controlPath: "gs://automation_control_test/branch"
