// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Stages configuration and system prompts into agent/config.json for local development.
 *
 * This mirrors the config assembly performed by narratives/deploy.sh for production,
 * layering defaults/ with config/ overrides and inlining prompts into a single document
 * that the Python agent consumes.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const narrativesDir = path.resolve(scriptsDir, '..');
const defaultsDir = path.join(narrativesDir, 'defaults');
const configDir = path.join(narrativesDir, 'config');
const agentDir = path.join(narrativesDir, 'agent');
const targetConfigFile = path.join(agentDir, 'config.json');

// 0. Load local environment variables from .env.local and .env
function loadEnv(filePath) {
  if (!fs.existsSync(filePath)) return;
  const content = fs.readFileSync(filePath, 'utf8');
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf('=');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = val;
    }
  }
}

loadEnv(path.join(narrativesDir, '.env.local'));
loadEnv(path.join(narrativesDir, '.env'));

// 1. Load baseline agent-config.json from defaults/
const baseConfigPath = path.join(defaultsDir, 'agent-config.json');
if (!fs.existsSync(baseConfigPath)) {
  console.error(`FATAL: ${baseConfigPath} not found.`);
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(baseConfigPath, 'utf8'));

// 2. Overlay config/agent-config.json if present
const overrideConfigPath = path.join(configDir, 'agent-config.json');
if (fs.existsSync(overrideConfigPath)) {
  try {
    const overrides = JSON.parse(fs.readFileSync(overrideConfigPath, 'utf8'));
    Object.assign(config, overrides);
  } catch (err) {
    console.warn(`Warning: Could not parse ${overrideConfigPath}: ${err.message}`);
  }
}

// 3. Inline prompts from defaults/prompts/ overlaid by config/prompts/
const promptSlots = ['mcp', 'synthesis', 'follow_up'];
const prompts = {};

for (const slot of promptSlots) {
  const defaultPromptPath = path.join(defaultsDir, 'prompts', `${slot}.md`);
  const overridePromptPath = path.join(configDir, 'prompts', `${slot}.md`);

  if (fs.existsSync(overridePromptPath)) {
    prompts[slot] = fs.readFileSync(overridePromptPath, 'utf8');
  } else if (fs.existsSync(defaultPromptPath)) {
    prompts[slot] = fs.readFileSync(defaultPromptPath, 'utf8');
  }
}

config.prompts = prompts;

// 4. Handle Gemini API Key: check environment, preserve existing, or placeholder
let existingKey = '';
if (fs.existsSync(targetConfigFile)) {
  try {
    const existing = JSON.parse(fs.readFileSync(targetConfigFile, 'utf8'));
    if (existing?.gemini?.api_key && !existing.gemini.api_key.startsWith('REPLACE_ME')) {
      existingKey = existing.gemini.api_key;
    }
  } catch {
    // Ignore existing parse errors
  }
}

const envApiKey = (process.env.GEMINI_API_KEY || '').trim();
const apiKey = envApiKey || existingKey || 'REPLACE_ME_WITH_GEMINI_API_KEY';

config.gemini = {
  ...(config.gemini || {}),
  api_key: apiKey,
};

// 5. Write to agent/config.json
fs.mkdirSync(agentDir, { recursive: true });
fs.writeFileSync(targetConfigFile, JSON.stringify(config, null, 2) + '\n', 'utf8');

// 6. Write agent/.env for agent dev runner (uv run --env-file .env ...)
const agentEnvPath = path.join(agentDir, '.env');
const localEnvPath = path.join(narrativesDir, '.env.local');
const defaultEnvPath = path.join(narrativesDir, '.env');

let envContent = '# Auto-generated by scripts/stage_config.mjs\n';
if (fs.existsSync(localEnvPath)) {
  envContent = fs.readFileSync(localEnvPath, 'utf8');
} else if (fs.existsSync(defaultEnvPath)) {
  envContent = fs.readFileSync(defaultEnvPath, 'utf8');
}
fs.writeFileSync(agentEnvPath, envContent, 'utf8');

console.log('✓ Staged agent configuration and environment into agent/');

