projectID: "datcom-store"
instance: "prophet-cache"
cluster: "prophet-cache-c1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-store-resources/dataflow/tmp"
dataPath: "gs://datcom-store"
controlPath: "gs://datcom-control/base"
appProfileID: "batch"
maxNumWorkers: 1000
